# 公共配置文件
spring:
  application:
    name: fishmanChat-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupao
    username: root
    password: 030610CHENyu
  # session 失效时间
  session:
    store-type: redis
  jackson:
    time-zone: GMT+8
    date-format: java.text.SimpleDateFormat
  mail:
    host: smtp.163.com
    username: cy13692810010@163.com
    password: 7894561230chenyu
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  #redis配置
  redis:
    port: 6379
    host: localhost
    database: 0
    #修改redis的数据库，redis带有16个数据库
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
        http-only: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: on
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #SQL的日志打印
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
knife4j:
  enable: true
  openapi:
    title: 接口文档
    description: "用户匹配系统"
    email: cy13692810010@163.com
    version: v2.0.0
    concat: fishman
    group:
      yupao:
        group-name: fishmanChat
        api-rule: package
        api-rule-resources:
          - com.fishman.usercenter.controller
fishman:
  img: /img/
  job: "0 0 0 * * ? *"
  enable-bloom-filter: false
  use-short-messaging-service: true